name: test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        perl:
          [
            "5.40",
            "5.38",
            "5.36",
            "5.34",
            "5.32",
            "5.30",
            "5.28",
            "5.26",
            "5.24",
            "5.22",
            "5.20",
            "5.18"
          ]
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Install dependencies
        run: |
          cpanm -nq Alien::Build Alien::Build::MB
          cpanm -nq Alien::Build::Plugin::Download::GitHub
          cpanm -nq --installdeps --with-develop --with-recommends .
      - name: Build module
        run: |
          perl Build.PL
          ./Build
      - name: Run test
        env:
          ALIEN_TURSO_CLI_TEST: 1
        run: ./Build test

